
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 07 20:06:41 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 17;
  public static final int DIVASG = 31;
  public static final int RIGHT_PAREN = 6;
  public static final int DVOTACKA = 39;
  public static final int RIGHT_BRACKET = 8;
  public static final int INCREMENT = 21;
  public static final int CONST = 19;
  public static final int VECEJEDNAKO = 45;
  public static final int HASH = 35;
  public static final int MINUS = 15;
  public static final int DECREMENT = 22;
  public static final int SEMICOLON = 10;
  public static final int SUBASG = 29;
  public static final int MULASG = 30;
  public static final int MANJEJEDNAKO = 47;
  public static final int JEDNAKO = 42;
  public static final int UPITNIK = 40;
  public static final int COMMA = 20;
  public static final int LEFT_BRACE = 3;
  public static final int PLUS = 14;
  public static final int MULTIPLY = 18;
  public static final int ASSIGN = 13;
  public static final int ADDASG = 28;
  public static final int EOF = 0;
  public static final int RETURN = 33;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int DVOTACKA2 = 41;
  public static final int RIGHT_BRACE = 4;
  public static final int NUMBER = 25;
  public static final int MOD = 16;
  public static final int IDENT = 24;
  public static final int VOID = 9;
  public static final int MODASG = 32;
  public static final int MANJE = 46;
  public static final int VECE = 44;
  public static final int READ = 11;
  public static final int KAPICA = 37;
  public static final int CHARCONST = 26;
  public static final int BOOLCONST = 27;
  public static final int PROG = 2;
  public static final int LEFT_PAREN = 5;
  public static final int AT = 34;
  public static final int CRTA = 38;
  public static final int DOLAR = 36;
  public static final int LEFT_BRACKET = 7;
  public static final int PRINT = 12;
  public static final int NEJEDNAKO = 43;
}

